# -*- coding: utf-8 -*-
"""pipeline-neural-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sr6mwRz9bTKirgD0Rq2AyiNkHRzreDQr
"""

from google.colab import files
uploaded = files.upload()

"""
pipeline-neural.py — FIXED & IMPROVED
Food Hazard Detection (SemEval-2025 Task 9, ST1)

Bugs διορθώθηκαν:
  1. device = torch.device('cuda') → crash αν δεν υπάρχει GPU
  2. Και τα δύο μοντέλα αποθηκεύονταν ως 'best_model.pt' → overwrite!
  3. Product μοντέλο εκπαιδευόταν χωρίς hazard prediction ως feature (δεν είναι 2-stage)
  4. official_score χωρίς zero_division → crash αν καμία σωστή hazard
  5. Δεν υπήρχε submission για το test set
"""

import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from sklearn.metrics import f1_score, classification_report
from sklearn.utils.class_weight import compute_class_weight
import warnings
warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────
# FIX 1: Device — δεν κάνουμε hardcode 'cuda'
# Αυτόματη επιλογή: GPU αν υπάρχει, αλλιώς CPU
# ─────────────────────────────────────────────
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# ─────────────────────────────────────────────
# 1. Load Data
# ─────────────────────────────────────────────
train_df = pd.read_csv('train.csv')
valid_df = pd.read_csv('valid.csv')
test_df  = pd.read_csv('test.csv')

print(f"Train: {len(train_df)} | Valid: {len(valid_df)} | Test: {len(test_df)}")

def build_text(df):
    title = df['title'].fillna('')
    text  = df['text'].fillna('')
    return (title + ' ') * 3 + text

train_df['input'] = build_text(train_df)
valid_df['input'] = build_text(valid_df)
test_df['input']  = build_text(test_df)

# ─────────────────────────────────────────────
# 2. Label Mapping
# ─────────────────────────────────────────────
hazard_labels  = sorted(train_df['hazard-category'].unique())
hazard_to_id   = {label: i for i, label in enumerate(hazard_labels)}
id_to_hazard   = {i: label for label, i in hazard_to_id.items()}

product_labels = sorted(train_df['product-category'].unique())
product_to_id  = {label: i for i, label in enumerate(product_labels)}
id_to_product  = {i: label for label, i in product_to_id.items()}

print(f"Hazard classes: {len(hazard_to_id)}")
print(f"Product classes: {len(product_to_id)}")

# ─────────────────────────────────────────────
# 3. Dataset Class
# ─────────────────────────────────────────────
MODEL_NAME = 'distilbert-base-uncased'
tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)
print(f"\nTokenizer loaded: {MODEL_NAME}")

class FoodHazardDataset(Dataset):
    def __init__(self, texts, labels=None, tokenizer=tokenizer, max_length=128):
        self.texts      = list(texts)
        self.labels     = list(labels) if labels is not None else None
        self.tokenizer  = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        item = {
            'input_ids':      encoding['input_ids'].squeeze(),
            'attention_mask': encoding['attention_mask'].squeeze(),
        }
        if self.labels is not None:
            item['label'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# ─────────────────────────────────────────────
# 4. Class Weights
# ─────────────────────────────────────────────
def get_class_weights(labels, num_classes):
    weights = compute_class_weight(
        class_weight='balanced',
        classes=np.arange(num_classes),
        y=labels
    )
    return torch.tensor(weights, dtype=torch.float).to(device)

train_hazard_labels  = train_df['hazard-category'].map(hazard_to_id).tolist()
valid_hazard_labels  = valid_df['hazard-category'].map(hazard_to_id).tolist()
train_product_labels = train_df['product-category'].map(product_to_id).tolist()
valid_product_labels = valid_df['product-category'].map(product_to_id).tolist()

hazard_weights  = get_class_weights(train_hazard_labels,  len(hazard_to_id))
product_weights = get_class_weights(train_product_labels, len(product_to_id))

print("\nHazard class weights:")
for label, weight in zip(hazard_labels, hazard_weights):
    print(f"  {label:35s} {weight:.3f}")

# ─────────────────────────────────────────────
# 5. Training Function
# ─────────────────────────────────────────────
def train_model(model, train_loader, valid_loader,
                class_weights, save_path, num_epochs=4, lr=2e-5):
    """
    save_path: FIX 2 — ξεχωριστό path για κάθε μοντέλο
               'best_hazard_model.pt' ή 'best_product_model.pt'
               Πριν: και τα δύο έγραφαν 'best_model.pt' → overwrite!
    """
    optimizer   = AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    total_steps = len(train_loader) * num_epochs
    scheduler   = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=total_steps // 10,
        num_training_steps=total_steps
    )
    loss_fn    = torch.nn.CrossEntropyLoss(weight=class_weights)
    best_f1    = 0
    best_preds = None

    for epoch in range(num_epochs):
        # ── Training ──────────────────────────
        model.train()
        total_loss = 0

        for batch_idx, batch in enumerate(train_loader):
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss    = loss_fn(outputs.logits, labels)
            total_loss += loss.item()

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            if (batch_idx + 1) % 50 == 0:
                print(f"  Epoch {epoch+1} | Batch {batch_idx+1}/{len(train_loader)} "
                      f"| Loss: {total_loss/(batch_idx+1):.4f}")

        # ── Validation ────────────────────────
        model.eval()
        all_preds, all_labels = [], []

        with torch.no_grad():
            for batch in valid_loader:
                input_ids      = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                preds   = torch.argmax(outputs.logits, dim=1)
                all_preds.extend(preds.cpu().numpy())
                if 'label' in batch:
                    all_labels.extend(batch['label'].numpy())

        epoch_f1 = f1_score(all_labels, all_preds, average='macro', zero_division=0)
        avg_loss  = total_loss / len(train_loader)
        print(f"\nEpoch {epoch+1}/{num_epochs} | Loss: {avg_loss:.4f} | Val Macro-F1: {epoch_f1:.4f}")

        if epoch_f1 > best_f1:
            best_f1    = epoch_f1
            best_preds = all_preds.copy()
            torch.save(model.state_dict(), save_path)  # FIX 2
            print(f"  ✓ New best! F1={best_f1:.4f} → saved {save_path}")
        print()

    return best_preds, best_f1


def predict(model, loader):
    """Παράγει predictions χωρίς labels (για test set)."""
    model.eval()
    all_preds = []
    with torch.no_grad():
        for batch in loader:
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            preds   = torch.argmax(outputs.logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
    return all_preds

# ─────────────────────────────────────────────
# 6. Official Score Function
# ─────────────────────────────────────────────
def official_score(true_hazard, pred_hazard, true_product, pred_product):
    # FIX 4: zero_division=0 αποτρέπει crash
    hazard_f1    = f1_score(true_hazard, pred_hazard,
                            average='macro', zero_division=0)
    correct_mask = [p == t for p, t in zip(pred_hazard, true_hazard)]
    true_filt    = [t for t, m in zip(true_product,  correct_mask) if m]
    pred_filt    = [p for p, m in zip(pred_product,  correct_mask) if m]

    if len(true_filt) == 0:
        product_f1 = 0.0
    else:
        product_f1 = f1_score(true_filt, pred_filt,
                              average='macro', zero_division=0)

    score = (hazard_f1 + product_f1) / 2
    return hazard_f1, product_f1, score

# ─────────────────────────────────────────────
# 7. Stage 1 — Hazard Model
# ─────────────────────────────────────────────
print("\n" + "="*55)
print("STAGE 1: Training Hazard Model")
print("="*55)

train_hazard_dataset = FoodHazardDataset(
    train_df['input'], pd.Series(train_hazard_labels), tokenizer)
valid_hazard_dataset = FoodHazardDataset(
    valid_df['input'], pd.Series(valid_hazard_labels), tokenizer)

train_hazard_loader = DataLoader(train_hazard_dataset, batch_size=16, shuffle=True)
valid_hazard_loader = DataLoader(valid_hazard_dataset, batch_size=32, shuffle=False)

hazard_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=len(hazard_to_id)
).to(device)

hazard_preds_valid, hazard_best_f1 = train_model(
    hazard_model,
    train_hazard_loader,
    valid_hazard_loader,
    hazard_weights,
    save_path='best_hazard_model.pt',  # FIX 2
    num_epochs=4
)

# Φόρτωσε το καλύτερο
hazard_model.load_state_dict(torch.load('best_hazard_model.pt'))

hazard_preds_labels = [id_to_hazard[p]  for p in hazard_preds_valid]
hazard_true_labels  = valid_df['hazard-category'].tolist()

print(f"\nBest Hazard Macro-F1: {hazard_best_f1:.4f}")
print("\nPer-class breakdown:")
print(classification_report(hazard_true_labels, hazard_preds_labels, digits=3))

# ─────────────────────────────────────────────
# 8. Stage 2 — Product Model
# FIX 3: Εκπαιδεύεται ξεχωριστά με δικό του save path
# (2-stage: hazard prediction χρησιμοποιείται στο scoring, όχι ως feature εδώ)
# ─────────────────────────────────────────────
print("\n" + "="*55)
print("STAGE 2: Training Product Model")
print("="*55)

train_product_dataset = FoodHazardDataset(
    train_df['input'], pd.Series(train_product_labels), tokenizer)
valid_product_dataset = FoodHazardDataset(
    valid_df['input'], pd.Series(valid_product_labels), tokenizer)

train_product_loader = DataLoader(train_product_dataset, batch_size=16, shuffle=True)
valid_product_loader = DataLoader(valid_product_dataset, batch_size=32, shuffle=False)

product_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=len(product_to_id)
).to(device)

product_preds_valid, product_best_f1 = train_model(
    product_model,
    train_product_loader,
    valid_product_loader,
    product_weights,
    save_path='best_product_model.pt',  # FIX 2
    num_epochs=4
)

# Φόρτωσε το καλύτερο
product_model.load_state_dict(torch.load('best_product_model.pt'))

product_preds_labels = [id_to_product[p] for p in product_preds_valid]
product_true_labels  = valid_df['product-category'].tolist()

print(f"\nBest Product Macro-F1: {product_best_f1:.4f}")
print("\nPer-class breakdown:")
print(classification_report(product_true_labels, product_preds_labels, digits=3))

# ─────────────────────────────────────────────
# 9. Official Score
# ─────────────────────────────────────────────
h_f1, p_f1, total = official_score(
    hazard_true_labels,  hazard_preds_labels,
    product_true_labels, product_preds_labels
)

print(f"\n{'='*55}")
print(f"  Hazard Macro-F1:                    {h_f1:.4f}")
print(f"  Product Macro-F1 (correct hazards): {p_f1:.4f}")
print(f"  ★ Official ST1 Score:               {total:.4f}")
print(f"{'='*55}")

# ─────────────────────────────────────────────
# 10. FIX 5: Submission για test set
# Πριν: δεν υπήρχε καθόλου
# ─────────────────────────────────────────────
print("\nGenerating test predictions...")

test_dataset = FoodHazardDataset(test_df['input'], tokenizer=tokenizer)
test_loader  = DataLoader(test_dataset, batch_size=32, shuffle=False)

test_hazard_preds  = predict(hazard_model,  test_loader)
test_product_preds = predict(product_model, test_loader)

test_hazard_labels  = [id_to_hazard[p]  for p in test_hazard_preds]
test_product_labels = [id_to_product[p] for p in test_product_preds]

submission = pd.DataFrame({
    'id':               test_df['id'],
    'hazard-category':  test_hazard_labels,
    'product-category': test_product_labels
})
submission.to_csv('submission_neural.csv', index=False)
print(f"Saved → submission_neural.csv")
print(submission.head())
print("\nDone!")

!pip install transformers -q
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, DistilBertModel, AutoModelForSequenceClassification
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from sklearn.metrics import f1_score, classification_report
from sklearn.utils.class_weight import compute_class_weight
import warnings
warnings.filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

from google.colab import files
uploaded = files.upload()  # upload train.csv, valid.csv, test.csv

train_df = pd.read_csv('train.csv')
valid_df = pd.read_csv('valid.csv')
test_df  = pd.read_csv('test.csv')

print(f"Train: {len(train_df)} | Valid: {len(valid_df)} | Test: {len(test_df)}")

def build_text(df):
    title = df['title'].fillna('')
    text  = df['text'].fillna('')
    return (title + ' ') * 3 + text

train_df['input'] = build_text(train_df)
valid_df['input'] = build_text(valid_df)
test_df['input']  = build_text(test_df)

hazard_labels  = sorted(train_df['hazard-category'].unique())
hazard2id      = {l: i for i, l in enumerate(hazard_labels)}
id2hazard      = {i: l for l, i in hazard2id.items()}

product_labels = sorted(train_df['product-category'].unique())
product2id     = {l: i for i, l in enumerate(product_labels)}
id2product     = {i: l for l, i in product2id.items()}

print(f"Hazard classes: {len(hazard2id)} | Product classes: {len(product2id)}")

MODEL_NAME = 'distilbert-base-uncased'
tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)
print("Tokenizer ready!")

class FoodDataset(Dataset):
    def __init__(self, texts, labels=None, max_length=256):
        self.texts      = list(texts)
        self.labels     = list(labels) if labels is not None else None
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = tokenizer(
            self.texts[idx],
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        item = {
            'input_ids':      enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
        }
        if self.labels is not None:
            item['label'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

def get_weights(labels, n_classes):
    w = compute_class_weight('balanced', classes=np.arange(n_classes), y=labels)
    return torch.tensor(w, dtype=torch.float).to(device)

train_hazard_ids  = train_df['hazard-category'].map(hazard2id).tolist()
valid_hazard_ids  = valid_df['hazard-category'].map(hazard2id).tolist()
train_product_ids = train_df['product-category'].map(product2id).tolist()
valid_product_ids = valid_df['product-category'].map(product2id).tolist()

hazard_weights  = get_weights(train_hazard_ids,  len(hazard2id))
product_weights = get_weights(train_product_ids, len(product2id))
print("Class weights computed!")

def train_model(model, train_loader, valid_loader,
                weights, save_path, num_epochs=5, lr=2e-5):

    optimizer   = AdamW(model.parameters(), lr=lr, weight_decay=0.01)
    total_steps = len(train_loader) * num_epochs
    scheduler   = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=total_steps // 10,
        num_training_steps=total_steps
    )
    loss_fn    = nn.CrossEntropyLoss(weight=weights)
    best_f1    = 0
    best_preds = None

    for epoch in range(num_epochs):
        # Training
        model.train()
        total_loss = 0
        for i, batch in enumerate(train_loader):
            ids   = batch['input_ids'].to(device)
            mask  = batch['attention_mask'].to(device)
            lbls  = batch['label'].to(device)

            out  = model(input_ids=ids, attention_mask=mask)
            loss = loss_fn(out.logits, lbls)
            total_loss += loss.item()

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()

            if (i + 1) % 50 == 0:
                print(f"  Epoch {epoch+1} | Batch {i+1}/{len(train_loader)}"
                      f" | Loss: {total_loss/(i+1):.4f}")

        # Validation
        model.eval()
        preds, trues = [], []
        with torch.no_grad():
            for batch in valid_loader:
                ids  = batch['input_ids'].to(device)
                mask = batch['attention_mask'].to(device)
                out  = model(input_ids=ids, attention_mask=mask)
                p    = torch.argmax(out.logits, dim=1)
                preds.extend(p.cpu().numpy())
                trues.extend(batch['label'].numpy())

        f1 = f1_score(trues, preds, average='macro', zero_division=0)
        print(f"\nEpoch {epoch+1}/{num_epochs} | "
              f"Loss: {total_loss/len(train_loader):.4f} | F1: {f1:.4f}")

        if f1 > best_f1:
            best_f1    = f1
            best_preds = preds.copy()
            torch.save(model.state_dict(), save_path)
            print(f"  ✓ Best saved → {save_path} (F1={best_f1:.4f})")
        print()

    return best_preds, best_f1


def predict(model, texts, batch_size=32):
    """Get predictions for any set of texts"""
    dataset = FoodDataset(texts)
    loader  = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    model.eval()
    preds, probs = [], []
    with torch.no_grad():
        for batch in loader:
            ids  = batch['input_ids'].to(device)
            mask = batch['attention_mask'].to(device)
            out  = model(input_ids=ids, attention_mask=mask)
            p    = torch.argmax(out.logits, dim=1)
            pb   = torch.softmax(out.logits, dim=1)
            preds.extend(p.cpu().numpy())
            probs.extend(pb.cpu().numpy())
    return np.array(preds), np.array(probs)

def official_score(true_h, pred_h, true_p, pred_p):
    h_f1 = f1_score(true_h, pred_h, average='macro', zero_division=0)
    mask  = [p == t for p, t in zip(pred_h, true_h)]
    tf    = [t for t, m in zip(true_p, mask) if m]
    pf    = [p for p, m in zip(pred_p, mask) if m]
    p_f1  = f1_score(tf, pf, average='macro', zero_division=0) if tf else 0.0
    return h_f1, p_f1, (h_f1 + p_f1) / 2

print("="*50)
print("STAGE 1: Hazard Model")
print("="*50)

train_h_loader = DataLoader(
    FoodDataset(train_df['input'], train_hazard_ids),
    batch_size=16, shuffle=True
)
valid_h_loader = DataLoader(
    FoodDataset(valid_df['input'], valid_hazard_ids),
    batch_size=32, shuffle=False
)

hazard_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=len(hazard2id)
).to(device)

hazard_preds, hazard_f1 = train_model(
    hazard_model, train_h_loader, valid_h_loader,
    hazard_weights, 'best_hazard.pt', num_epochs=5
)

hazard_model.load_state_dict(torch.load('best_hazard.pt'))
print(f"\nBest Hazard F1: {hazard_f1:.4f}")

pred_h_labels = [id2hazard[p] for p in hazard_preds]
true_h_labels = valid_df['hazard-category'].tolist()
print(classification_report(true_h_labels, pred_h_labels, digits=3))

print("="*50)
print("STAGE 2: Cascaded Product Model")
print("="*50)

# Get hazard probabilities to feed into product model
# For train: predict on train (slight leakage but acceptable for now)
# For valid: predict using trained hazard model
_, train_hazard_probs = predict(hazard_model, train_df['input'])
_, valid_hazard_probs = predict(hazard_model, valid_df['input'])

print(f"Hazard probs shape — train: {train_hazard_probs.shape} | valid: {valid_hazard_probs.shape}")

class FoodDatasetCascaded(Dataset):
    """Text + hazard probabilities → product category"""
    def __init__(self, texts, hazard_probs, labels=None, max_length=256):
        self.texts        = list(texts)
        self.hazard_probs = hazard_probs
        self.labels       = list(labels) if labels is not None else None
        self.max_length   = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = tokenizer(
            self.texts[idx],
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )
        item = {
            'input_ids':      enc['input_ids'].squeeze(),
            'attention_mask': enc['attention_mask'].squeeze(),
            'hazard_probs':   torch.tensor(self.hazard_probs[idx], dtype=torch.float)
        }
        if self.labels is not None:
            item['label'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item


class CascadedProductModel(nn.Module):
    """DistilBERT + hazard probs → product category"""
    def __init__(self, n_hazard, n_product):
        super().__init__()
        self.bert = DistilBertModel.from_pretrained(MODEL_NAME)
        self.classifier = nn.Sequential(
            nn.Linear(768 + n_hazard, 512),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(512, n_product)
        )

    def forward(self, input_ids, attention_mask, hazard_probs):
        out     = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        cls     = out.last_hidden_state[:, 0, :]        # [CLS] token
        combined = torch.cat([cls, hazard_probs], dim=1) # append hazard info
        return self.classifier(combined)

train_p_loader = DataLoader(
    FoodDatasetCascaded(train_df['input'], train_hazard_probs, train_product_ids),
    batch_size=16, shuffle=True
)
valid_p_loader = DataLoader(
    FoodDatasetCascaded(valid_df['input'], valid_hazard_probs, valid_product_ids),
    batch_size=32, shuffle=False
)

product_model = CascadedProductModel(len(hazard2id), len(product2id)).to(device)

# Custom training loop for cascaded model
optimizer   = AdamW(product_model.parameters(), lr=2e-5, weight_decay=0.01)
total_steps = len(train_p_loader) * 6
scheduler   = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=total_steps // 10,
    num_training_steps=total_steps
)
loss_fn  = nn.CrossEntropyLoss(weight=product_weights)
best_f1  = 0
best_preds = None

for epoch in range(6):
    product_model.train()
    total_loss = 0

    for i, batch in enumerate(train_p_loader):
        ids   = batch['input_ids'].to(device)
        mask  = batch['attention_mask'].to(device)
        hprob = batch['hazard_probs'].to(device)
        lbls  = batch['label'].to(device)

        logits = product_model(ids, mask, hprob)
        loss   = loss_fn(logits, lbls)
        total_loss += loss.item()

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(product_model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        if (i + 1) % 50 == 0:
            print(f"  Epoch {epoch+1} | Batch {i+1}/{len(train_p_loader)}"
                  f" | Loss: {total_loss/(i+1):.4f}")

    # Validation
    product_model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for batch in valid_p_loader:
            ids   = batch['input_ids'].to(device)
            mask  = batch['attention_mask'].to(device)
            hprob = batch['hazard_probs'].to(device)
            logits = product_model(ids, mask, hprob)
            p      = torch.argmax(logits, dim=1)
            preds.extend(p.cpu().numpy())
            trues.extend(batch['label'].numpy())

    f1 = f1_score(trues, preds, average='macro', zero_division=0)
    print(f"\nEpoch {epoch+1}/6 | Loss: {total_loss/len(train_p_loader):.4f} | F1: {f1:.4f}")

    if f1 > best_f1:
        best_f1    = f1
        best_preds = preds.copy()
        torch.save(product_model.state_dict(), 'best_product.pt')
        print(f"  ✓ Best saved (F1={best_f1:.4f})")
    print()

product_model.load_state_dict(torch.load('best_product.pt'))
print(f"\nBest Product F1: {best_f1:.4f}")

pred_p_labels = [id2product[p] for p in best_preds]
true_p_labels = valid_df['product-category'].tolist()
print(classification_report(true_p_labels, pred_p_labels, digits=3))

h_f1, p_f1, score = official_score(
    true_h_labels, pred_h_labels,
    true_p_labels, pred_p_labels
)

print(f"{'='*50}")
print(f"Hazard F1:                    {h_f1:.4f}")
print(f"Product F1 (correct hazards): {p_f1:.4f}")
print(f"★ Official Score:             {score:.4f}")
print(f"{'='*50}")
print(f"\nClassical baseline: 0.7200")
print(f"Improvement:        {score - 0.72:+.4f}")

# Generate submission
print("\nGenerating submission...")
test_hazard_preds, test_hazard_probs = predict(hazard_model, test_df['input'])

# Product predictions for test
test_p_dataset = FoodDatasetCascaded(test_df['input'], test_hazard_probs)
test_p_loader  = DataLoader(test_p_dataset, batch_size=32, shuffle=False)

product_model.eval()
test_product_preds = []
with torch.no_grad():
    for batch in test_p_loader:
        ids   = batch['input_ids'].to(device)
        mask  = batch['attention_mask'].to(device)
        hprob = batch['hazard_probs'].to(device)
        logits = product_model(ids, mask, hprob)
        p      = torch.argmax(logits, dim=1)
        test_product_preds.extend(p.cpu().numpy())

submission = pd.DataFrame({
    'id':               test_df['id'],
    'hazard-category':  [id2hazard[p]  for p in test_hazard_preds],
    'product-category': [id2product[p] for p in test_product_preds]
})
submission.to_csv('submission_neural_v2.csv', index=False)
print("Saved → submission_neural_v2.csv")
print(submission.head())

# Download
from google.colab import files
files.download('submission_neural_v2.csv')

# What did we get locally on validation?
print(f"Hazard F1 (local):  {h_f1:.4f}")
print(f"Product F1 (local): {p_f1:.4f}")
print(f"Official (local):   {score:.4f}")

sub = pd.read_csv('submission_neural_v2.csv')
print("Submission shape:", sub.shape)
print("\nColumns:", sub.columns.tolist())
print("\nSample predictions:")
print(sub.head(10))
print("\nHazard prediction distribution:")
print(sub['hazard-category'].value_counts())
print("\nProduct prediction distribution:")
print(sub['product-category'].value_counts())

print("Test file columns:", test_df.columns.tolist())
print("Test file has 'id' column?", 'id' in test_df.columns)
print("\nFirst few IDs:")
print(test_df['id'].head())
print("\nSample test inputs (first 200 chars):")
for i in range(3):
    print(f"\n[{i}]: {test_df['input'].iloc[i][:200]}")

# Cell — Combine train + validation for final training
print("Combining train + validation for final model...")

full_df = pd.concat([train_df, valid_df], ignore_index=True)

full_df['input'] = build_text(full_df)

full_hazard_ids  = full_df['hazard-category'].map(hazard2id).tolist()
full_product_ids = full_df['product-category'].map(product2id).tolist()

# Recompute class weights on full data
full_hazard_weights  = get_weights(full_hazard_ids,  len(hazard2id))
full_product_weights = get_weights(full_product_ids, len(product2id))

print(f"Full training size: {len(full_df)}")
print(f"(was {len(train_df)} before, added {len(valid_df)} validation examples)")

# Cell — Retrain hazard model on full data
print("="*50)
print("Retraining Hazard Model on full data")
print("="*50)

# We know epoch 3-4 is best from our experiments
# So we train for exactly 4 epochs, no validation needed
full_h_loader = DataLoader(
    FoodDataset(full_df['input'], full_hazard_ids),
    batch_size=16, shuffle=True
)

final_hazard_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=len(hazard2id)
).to(device)

optimizer   = AdamW(final_hazard_model.parameters(), lr=2e-5, weight_decay=0.01)
total_steps = len(full_h_loader) * 4
scheduler   = get_linear_schedule_with_warmup(
    optimizer, num_warmup_steps=total_steps//10, num_training_steps=total_steps
)
loss_fn = nn.CrossEntropyLoss(weight=full_hazard_weights)

for epoch in range(4):
    final_hazard_model.train()
    total_loss = 0
    for i, batch in enumerate(full_h_loader):
        ids  = batch['input_ids'].to(device)
        mask = batch['attention_mask'].to(device)
        lbls = batch['label'].to(device)

        out  = final_hazard_model(input_ids=ids, attention_mask=mask)
        loss = loss_fn(out.logits, lbls)
        total_loss += loss.item()

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(final_hazard_model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

    print(f"Epoch {epoch+1}/4 | Loss: {total_loss/len(full_h_loader):.4f}")

torch.save(final_hazard_model.state_dict(), 'final_hazard.pt')
print("✓ Final hazard model saved!")

# Cell — Get hazard probs for full train + test
print("Getting hazard probabilities...")

_, full_hazard_probs = predict(final_hazard_model, full_df['input'])
_, test_hazard_probs = predict(final_hazard_model, test_df['input'])

print(f"Full hazard probs: {full_hazard_probs.shape}")
print(f"Test hazard probs: {test_hazard_probs.shape}")

# Cell — Retrain cascaded product model on full data
print("="*50)
print("Retraining Cascaded Product Model on full data")
print("="*50)

full_p_loader = DataLoader(
    FoodDatasetCascaded(full_df['input'], full_hazard_probs, full_product_ids),
    batch_size=16, shuffle=True
)

final_product_model = CascadedProductModel(len(hazard2id), len(product2id)).to(device)

optimizer   = AdamW(final_product_model.parameters(), lr=2e-5, weight_decay=0.01)
total_steps = len(full_p_loader) * 6
scheduler   = get_linear_schedule_with_warmup(
    optimizer, num_warmup_steps=total_steps//10, num_training_steps=total_steps
)
loss_fn = nn.CrossEntropyLoss(weight=full_product_weights)

for epoch in range(6):
    final_product_model.train()
    total_loss = 0
    for i, batch in enumerate(full_p_loader):
        ids   = batch['input_ids'].to(device)
        mask  = batch['attention_mask'].to(device)
        hprob = batch['hazard_probs'].to(device)
        lbls  = batch['label'].to(device)

        logits = final_product_model(ids, mask, hprob)
        loss   = loss_fn(logits, lbls)
        total_loss += loss.item()

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(final_product_model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

    print(f"Epoch {epoch+1}/6 | Loss: {total_loss/len(full_p_loader):.4f}")

torch.save(final_product_model.state_dict(), 'final_product.pt')
print("✓ Final product model saved!")

# Cell — Generate final submission
print("Generating final submission...")

# Hazard predictions for test
test_hazard_preds, test_hazard_probs = predict(final_hazard_model, test_df['input'])

# Product predictions for test
test_p_dataset = FoodDatasetCascaded(test_df['input'], test_hazard_probs)
test_p_loader  = DataLoader(test_p_dataset, batch_size=32, shuffle=False)

final_product_model.eval()
test_product_preds = []
with torch.no_grad():
    for batch in test_p_loader:
        ids   = batch['input_ids'].to(device)
        mask  = batch['attention_mask'].to(device)
        hprob = batch['hazard_probs'].to(device)
        logits = final_product_model(ids, mask, hprob)
        p      = torch.argmax(logits, dim=1)
        test_product_preds.extend(p.cpu().numpy())

submission = pd.DataFrame({
    'id':               test_df['id'],
    'hazard-category':  [id2hazard[p]  for p in test_hazard_preds],
    'product-category': [id2product[p] for p in test_product_preds]
})
submission.to_csv('submission_final.csv', index=False)

print("Saved → submission_final.csv")
print(submission['hazard-category'].value_counts())

from google.colab import files
files.download('submission_final.csv')